select * from costumer limit 10;

-- what is the total revenue generated by male vs female costumers ?
select gender , SUM(purchase_amount) as revenue from costumer group by gender;

-- which costumer used a discount but still spent more than the everage puchased amount?
select customer_id, purchase_amount from costumer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from costumer);

-- which are the top 5 products wiht have the average review rating?
select item_purchased , round(AVG(review_rating),2) as average_review_rating from costumer
group by item_purchased 
order by AVG(review_rating) desc limit 5;

-- compare the average purchase amount between the standard and Express shipping?
select shipping_type, AVG(purchase_amount) from costumer
where shipping_type in ('standard','express')
group by shipping_type; 

-- do subscribed costumer spend more ? compare average spent and total revenue 
-- between subscriber and non-subscriber?
select subscription_status ,count(customer_id) as total_number,
AVG(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from costumer 
group by subscription_status
order by total_revenue,avg_spend desc;

-- Which 5 products have the highest percentage of purchases
-- where a discount was applied?
SELECT item_purchased,
ROUND(100.0* SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )/ COUNT(*),2) AS discount_rate
from costumer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;

-- segment costumer info new ,returning, and loyal based on their total 
-- numer of previous purchases , ad show the count of each segment?
with customer_type as (select customer_id,previous_purchases,
case 
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
     end as customer_segment
from costumer
)
select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment;


-- what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM costumer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM costumer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group? 
SELECT 
age_group,
    SUM(purchase_amount) AS total_revenue
FROM costumer
GROUP BY age_group
ORDER BY total_revenue desc;
